name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Sync and merge upstream nitobuendia/oura-custom-component with akeslo/ouraring-ha
      uses: dabreadman/sync-upstream-repo@v1.0.0.b
      with:
        # URL of gitHub public upstream repo
        upstream_repo: "https://github.com/nitobuendia/oura-custom-component.git"
        # Branch to merge from upstream (defaults to downstream branch)
        upstream_branch: main
        # Branch to merge into downstream
        downstream_branch: main
        # GitHub Bot token
        token: ${{ secrets.GITHUB_TOKEN }}
